---
title: "DSlecture11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(p8105.datasets)
library(tidyverse)
library(leaflet)
data(nyc_airbnb)
```

```{r}
str(nyc_airbnb)
nyc_airbnb %>% 
  count(room_type)
nyc_airbnb %>% 
  count(neighbourhood_group)
```

```{r}
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(borough= neighbourhood_group)
```

```{r}
nyc_airbnb %>% 
  count(borough, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price))+
  geom_point() +
  facet_grid(. ~ room_type)
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price = mean(price, na.rm = TRUE)) %>% 
  arrange(mean_price)

nyc_airbnb %>% 
  filter(
    borough == "Manhattan",
    price <= 1000
  ) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(.~room_type)
```

```{r}
nyc_airbnb %>% 
  filter(price < 500) %>% 
  sample_n(5000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.5)
```

```{r}
pal = colorNumeric("viridis", NULL)

nyc_airbnb %>% 
  filter(price < 500) %>% 
  sample_n(1000) %>% 
  mutate(
    label = str_c("<b>Stars:", stars, "<\b><br>Price:", price, sep = "")
  ) %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat, ~long, radius = 1, popup = ~ label, color = ~pal(price))
```






